console.log('Hello world');

console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');
console.log('make team effort');